In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

URL = 'https://www.independent.co.uk/sport/football/euro-2020-squads-teams-b1848825.html'
page = requests.get(URL)

soup = BeautifulSoup(page.content, 'html.parser')

In [2]:
info = []
squad_info = soup.find_all('p')
for squad_ele in squad_info :
  
  players = squad_ele.text.replace('\ufeff','')
  if ':' in players and 'Spain' not in players :
    info.append(players)

In [8]:
teams = []
team = soup.find_all('div',{'class':"sc-qWSGh iSUKoQ"})
for i in team :
  ele = i.text
  if 'Group' not in ele :
    
   teams.append([ele for i in range(4)])

In [9]:
flatten = [item for sublist in teams for item in sublist]
print(len(flatten),len(info))

96 96

In [10]:
d = {'Country': flatten, 'Meta' : info}
draft = pd.DataFrame(d)
draft['Type'] = draft['Meta'].str.split(':').str[0].str.rstrip('s')
draft['Refined'] = draft['Meta'].str.split(':').str[1].str.lstrip()
draft

     Country  ...                                            Refined
0      Italy  ...  Gianluigi Donnarumma (Milan), Alex Meret (Napo...
1      Italy  ...  Francesco Acerbi (Lazio), Alessandro Bastoni (...
2      Italy  ...  Nicolò Barella (Inter), Federico Bernardeschi ...
3      Italy  ...  Andrea Belotti (Torino), Domenico Berardi (Sas...
4     Turkey  ...  Altay Bayındır (Fenerbahçe), Mert Günok (İstan...
..       ...  ...                                                ...
91  Portugal  ...  João Félix (Atlético Madrid), Diogo Jota (Live...
92    France  ...  Hugo Lloris (Tottenham), Mike Maignan (Milan),...
93    France  ...  Lucas Digne (Everton), Léo Dubois (Lyon), Luca...
94    France  ...  Kingsley Coman (Bayern), N’Golo Kanté (Chelsea...
95    France  ...  Wissam Ben Yedder (Monaco), Karim Benzema (Rea...

[96 rows x 4 columns]

In [11]:
#draft['Refined'].to_list()
play = []
for i in draft['Refined'].to_list() :
  new = i.split(',')
  for j in new :
    j = j.lstrip()
    play.append(j)
play_dict = {'Players':play}
players_db = pd.DataFrame(play_dict)
players_db['Name']  = players_db['Players'].str.split("(").str[0].str.rstrip('')
players_db['Club'] = players_db['Players'].str.split("(").str[1].str.rstrip(')')
players_db['Club'] = players_db['Club'].str.rstrip(').')
players_db

                              Players                   Name             Club
0        Gianluigi Donnarumma (Milan)  Gianluigi Donnarumma             Milan
1                 Alex Meret (Napoli)            Alex Meret            Napoli
2          Salvatore Sirigu (Torino).      Salvatore Sirigu            Torino
3            Francesco Acerbi (Lazio)      Francesco Acerbi             Lazio
4          Alessandro Bastoni (Inter)    Alessandro Bastoni             Inter
..                                ...                    ...              ...
616       Ousmane Dembélé (Barcelona)       Ousmane Dembélé         Barcelona
617          Olivier Giroud (Chelsea)        Olivier Giroud           Chelsea
618     Antoine Griezmann (Barcelona)     Antoine Griezmann         Barcelona
619               Kylian Mbappé (PSG)         Kylian Mbappé               PSG
620  Marcus Thuram (Mönchengladbach).         Marcus Thuram   Mönchengladbach

[621 rows x 3 columns]

In [12]:
country = []
typea = []
for i in players_db['Players'] :
  for m in range(len(draft)) :

    if i in draft['Refined'].to_list()[m] :
      
      country.append(draft['Country'][m])
      typea.append(draft['Type'][m])
players_db['Country'] = country
players_db['Role'] = typea
players_euro = players_db[['Name','Club','Country','Role']]
players_euro.to_csv('Players Euro.csv',index = False)
players_euro

                      Name             Club Country        Role
0    Gianluigi Donnarumma             Milan   Italy  Goalkeeper
1              Alex Meret            Napoli   Italy  Goalkeeper
2        Salvatore Sirigu            Torino   Italy  Goalkeeper
3        Francesco Acerbi             Lazio   Italy    Defender
4      Alessandro Bastoni             Inter   Italy    Defender
..                     ...              ...     ...         ...
616       Ousmane Dembélé         Barcelona  France     Forward
617        Olivier Giroud           Chelsea  France     Forward
618     Antoine Griezmann         Barcelona  France     Forward
619         Kylian Mbappé               PSG  France     Forward
620         Marcus Thuram   Mönchengladbach  France     Forward

[621 rows x 4 columns]